version: '3.8'
services:
  tataru-db:
    image: mongo
    container_name: tataru-db
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped